Repository ironcore-dev/cloud-provider-ironcore, pull requests merged in 2023-08, with the labels that each got.

#254 Extend Testing of Routes Controller Methods for Machine Network Interfaces
  pkg/cloudprovider/onmetal/constants.go
  pkg/cloudprovider/onmetal/instances_v2.go
  pkg/cloudprovider/onmetal/instances_v2_test.go
  pkg/cloudprovider/onmetal/routes.go
  pkg/cloudprovider/onmetal/routes_test.go
Labels: enhancement, size/L

#272 Handle type switching of LoadBalancer from Internal to Public and vice versa
  pkg/cloudprovider/onmetal/load_balancer.go
  pkg/cloudprovider/onmetal/load_balancer_test.go
Labels: size/L

#282 Refactor `networkInterfaceName` generation and clean up test cases
  pkg/cloudprovider/onmetal/routes.go
  pkg/cloudprovider/onmetal/routes_test.go
Labels: bug, size/XS
