Repository ironcore-dev/cloud-provider-ironcore, pull requests merged in 2023-07, with the labels that each got.

#241 Implement Routing Controller in cloud provider
  config/samples/cloud-config
  pkg/cloudprovider/onmetal/cloud.go
  pkg/cloudprovider/onmetal/cloud_test.go
  pkg/cloudprovider/onmetal/config.go
  pkg/cloudprovider/onmetal/config_test.go
  pkg/cloudprovider/onmetal/constants.go
  pkg/cloudprovider/onmetal/instances_v2.go
  pkg/cloudprovider/onmetal/instances_v2_test.go
  pkg/cloudprovider/onmetal/load_balancer_test.go
  pkg/cloudprovider/onmetal/routes.go
  pkg/cloudprovider/onmetal/routes_test.go
  pkg/cloudprovider/onmetal/suite_test.go
Labels: enhancement, size/XL

#244 Fix `NetworkInterface` lookup in `LoadBalancer` controller and refactor suite tests for `Routes` and `LoadBalancer`
  pkg/cloudprovider/onmetal/cloud_test.go
  pkg/cloudprovider/onmetal/instances_v2_test.go
  pkg/cloudprovider/onmetal/load_balancer.go
  pkg/cloudprovider/onmetal/load_balancer_test.go
  pkg/cloudprovider/onmetal/routes.go
  pkg/cloudprovider/onmetal/routes_test.go
  pkg/cloudprovider/onmetal/suite_test.go
Labels: bug, enhancement, size/XXL

#251 Fix `NetworkInterface` lookup in `DeleteRoutes` method
  pkg/cloudprovider/onmetal/routes.go
Labels: bug, size/S
