Repository ironcore-dev/cloud-provider-ironcore, pull requests merged in 2023-11, with the labels that each got.

#333 Update `golangci-lint` to in GH workflow
  .github/workflows/golangci-lint.yml
  .github/workflows/size-label.yml
Labels: size/XS, chore

#336 Add `golangci-lint` installation to `Makefile`
  Makefile
Labels: enhancement, size/S

#337 Refactor project name to `cloud-provider-ironcore`
  .github/dependabot.yml
  .github/workflows/publish-docker.yml
  .gitignore
  CODEOWNERS
  CODE_OF_CONDUCT.md
  Dockerfile
  Makefile
  README.md
  cmd/cloud-provider-ironcore/main.go
  config/config/secret.yaml
  config/kind/kustomization.yaml
  config/kind/patch-manager.yaml
  config/manager/manager.yaml
  docs/deployment/deploy_manually.md
  docs/development/setup.md
  go.mod
  go.sum
  pkg/cloudprovider/ironcore/cloud.go
  pkg/cloudprovider/ironcore/cloud_test.go
  pkg/cloudprovider/ironcore/config.go
  pkg/cloudprovider/ironcore/config_test.go
  pkg/cloudprovider/ironcore/constants.go
  pkg/cloudprovider/ironcore/instances_v2.go
  pkg/cloudprovider/ironcore/instances_v2_test.go
  pkg/cloudprovider/ironcore/load_balancer.go
  pkg/cloudprovider/ironcore/load_balancer_test.go
  pkg/cloudprovider/ironcore/routes.go
  pkg/cloudprovider/ironcore/routes_test.go
  pkg/cloudprovider/ironcore/suite_test.go
Labels: documentation, enhancement, size/XL, breaking
