Repository ironcore-dev/cloud-provider-ironcore, pull requests merged in 2023-06, with the labels that each got.

#227 Create LoadBalancer instance even if no Nodes are available
  pkg/cloudprovider/onmetal/load_balancer.go
  pkg/cloudprovider/onmetal/load_balancer_test.go
Labels: bug, size/S

#229 Improve LoadBalancer tests
  pkg/cloudprovider/onmetal/cloud_test.go
  pkg/cloudprovider/onmetal/instances_v2_test.go
  pkg/cloudprovider/onmetal/load_balancer.go
  pkg/cloudprovider/onmetal/load_balancer_test.go
  pkg/cloudprovider/onmetal/suite_test.go
Labels: enhancement, size/XL

#242 Update Go version and linters configuration
  .github/workflows/clean.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/test.yml
  .golangci.yaml
Labels: enhancement, size/S, chore
