Repository ironcore-dev/cloud-provider-ironcore, pull requests merged in 2024-05, with the labels that each got.

#415 Fix LoadBalancer port protocol assignment
  pkg/cloudprovider/ironcore/load_balancer.go
Labels: bug, size/XS

#430 Ignore `k8s.io/*` deps in dependabot configuration
  .github/dependabot.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/release-drafter.yml
  .github/workflows/size-label.yml
  Makefile
  go.mod
Labels: chore

#431 Add missing `k8s.io/*` deps to dependabot config
  .github/dependabot.yml
Labels: size/XS, chore
