Repository ironcore-dev/cloud-provider-ironcore, pull requests merged in 2024-11, with the labels that each got.

#464 Bump `k8s.io/*` deps to v0.30.4
  Makefile
  go.mod
  go.sum
Labels: enhancement, size/L

#469 Update reuse configuration
  .golangci.yml
  .reuse/dep5
Labels: size/XS, chore

#467 Improve logging in route controller
  Makefile
  pkg/cloudprovider/ironcore/routes.go
  pkg/cloudprovider/ironcore/routes_test.go
  pkg/cloudprovider/ironcore/suite_test.go
Labels: bug, enhancement, size/L

#471 Bump `k8s.io/*` deps to v0.30.7
  go.mod
  go.sum
Labels: size/M, chore
